const { useState, useEffect } = React;

function App() {
  const [dark, setDark] = useState(false);
  const [drawer, setDrawer] = useState(false);

  useEffect(() => {
    document.body.classList.toggle("dark-mode", dark);
  }, [dark]);

  return (
    <div className="min-h-screen w-full relative transition-colors">

      {/* NAVBAR */}
      <nav className={`fixed top-0 left-0 right-0 z-50 h-16 px-6 flex items-center justify-between backdrop-blur-md border-b 
        ${dark ? 'bg-[#020617]/90 border-white/5' : 'bg-white/90 border-slate-200'}`}>
        
        <button onClick={() => setDrawer(true)} className="p-2">
          ☰
        </button>

        <div className="font-black text-xl tracking-tight">
          IwanSena<span className={dark ? "text-teal-400" : "text-sky-600"}>.dev</span>
        </div>

        <button onClick={() => setDark(!dark)} className="text-xs font-mono">
          {dark ? "LIGHT" : "DARK"}
        </button>
      </nav>

      {/* DRAWER */}
      {drawer && (
        <div className="fixed inset-0 z-40">
          <div className="absolute inset-0 bg-black/60" onClick={() => setDrawer(false)} />
          <div className={`absolute left-0 top-0 bottom-0 w-72 p-8 
            ${dark ? 'bg-[#020617]' : 'bg-white'}`}>
            <ul className="space-y-4 font-bold">
              <li>Home</li>
              <li>Blog</li>
              <li>Projects</li>
              <li>Store</li>
            </ul>
          </div>
        </div>
      )}

      {/* CONTENT */}
      <main className="pt-24 px-6 max-w-6xl mx-auto">
        <h1 className="text-3xl font-black mb-10">
          Transmissions Feed
        </h1>

        {/* EMPTY STATE */}
        <div className="text-center py-32 opacity-60 font-mono">
          NO ARTICLES YET<br/>
          CONTENT WILL BE GENERATED BY SSG
        </div>
      </main>

      {/* FOOTER */}
      <footer className={`mt-40 p-10 text-white 
        ${dark ? 'bg-[#0c4a6e]' : 'bg-[#0d9488]'}`}>
        <div className="max-w-6xl mx-auto text-center space-y-4">
          <div className="font-black text-2xl">IwanSena.dev</div>
          <div className="flex justify-center gap-4">
            <a href="#">GitHub</a>
            <a href="#">Telegram</a>
            <a href="#">LinkedIn</a>
            <a href="#">Instagram</a>
          </div>
          <div className="text-xs opacity-70">
            © 2025 IWANSENA_LOGS — ALL SYSTEMS GO
          </div>
        </div>
      </footer>

    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
